/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Version"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Status"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SandboxList"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            image?: string;
            /** @description like 1h; null keeps it until killed; absent = default */
            ttl?: string | null;
            /** @enum {string} */
            network?: "internet" | "none";
            cpu?: string;
            memory?: string;
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description killed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/exec": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            cmd: string;
            /** @description seconds; null = no limit */
            timeout?: number | null;
            background?: boolean;
            env?: {
              [key: string]: string;
            };
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ExecResult"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/fork": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            count?: number;
            ttl?: string | null;
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SandboxList"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/extend": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description null keeps it until killed */
            ttl: string | null;
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/files": {
    parameters: {
      query: {
        /** @description relative to /workspace */
        path: string;
      };
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          /** @description relative to /workspace */
          path: string;
        };
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description file bytes */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/octet-stream": string;
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put: {
      parameters: {
        query: {
          /** @description relative to /workspace */
          path: string;
        };
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      /** @description up to 100 MB */
      requestBody: {
        content: {
          "application/octet-stream": string;
        };
      };
      responses: {
        /** @description written */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header: {
          "X-Dawnbx": "1";
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            username: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description signed in; sets the session cookie */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Principal"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description signed out */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Principal"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            old: string;
            new: string;
          };
        };
      };
      responses: {
        /** @description changed; every session of the user ends */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              keys: components["schemas"]["Key"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @description Go duration like "720h"; empty = never expires */
            ttl?: string;
            /** @description admins only */
            org?: string;
          };
        };
      };
      responses: {
        /** @description the token is shown only here */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              key: string;
              info: components["schemas"]["Key"];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/keys/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          key: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description revoked */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description latest 200 events */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              events: components["schemas"]["Event"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orgs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              orgs: components["schemas"]["Org"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            id: string;
            name?: string;
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              users: components["schemas"]["User"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            username: string;
            password: string;
            org?: string;
            /** @enum {string} */
            role?: "member" | "admin";
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: components["parameters"]["username"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          username: components["parameters"]["username"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{username}/password": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: components["parameters"]["username"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          username: components["parameters"]["username"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            password: string;
          };
        };
      };
      responses: {
        /** @description changed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/nodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              nodes: components["schemas"]["Node"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/nodes/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description install command for a new worker (audited) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              command: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/nodes/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description removed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      code: string;
      message: string;
      hint?: string;
    };
    Version: {
      version: string;
      api: string;
    };
    Status: {
      version: string;
      free_pct: number;
      warm: number;
      pool_size: number;
    };
    Sandbox: {
      id: string;
      image: string;
      /** @enum {string} */
      status: "running" | "stopped" | "deleting";
      /** @description why it stopped */
      reason?: string;
      parent?: string;
      network: string;
      /** Format: date-time */
      created: string;
      /**
       * Format: date-time
       * @description null = kept until killed
       */
      expires_at: string | null;
      /** Format: date-time */
      restarted_at: string | null;
      org: string;
      node?: string;
      warnings?: string[];
    };
    SandboxList: {
      sandboxes: components["schemas"]["Sandbox"][];
    };
    ExecResult: {
      exit_code: number;
      stdout: string;
      stderr: string;
      /** @description background only */
      pid?: number;
      /** @description background only */
      log?: string;
    };
    Principal: {
      org: string;
      /** @description dashboard sessions */
      user?: string;
      /** @description API keys */
      key_id?: string;
      admin: boolean;
    };
    Key: {
      id: string;
      org: string;
      name: string;
      /** Format: date-time */
      created: string;
      created_by: string;
      /** Format: date-time */
      last_used: string | null;
      /** Format: date-time */
      expires: string | null;
      /** Format: date-time */
      revoked: string | null;
    };
    Event: {
      /** Format: date-time */
      at: string;
      org: string;
      actor: string;
      action: string;
      target: string;
    };
    Org: {
      id: string;
      name: string;
      /** Format: date-time */
      created: string;
    };
    User: {
      id: string;
      org: string;
      username: string;
      /** @enum {string} */
      role: "member" | "admin";
      /** Format: date-time */
      created: string;
    };
    Node: {
      name: string;
      /** @enum {string} */
      role: "server" | "worker";
      ready: boolean;
      /**
       * Format: date-time
       * @description last Ready change
       */
      since: string;
      /** Format: date-time */
      heartbeat: string;
      ip: string;
      kubelet: string;
      sandboxes: number;
    };
  };
  responses: {
    /** @description error */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    id: string;
    username: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
