/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Version"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Status"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SandboxList"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            image?: string;
            /** @description like 1h; null keeps it until killed; absent = default */
            ttl?: string | null;
            /** @enum {string} */
            network?: "internet" | "none";
            cpu?: string;
            memory?: string;
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description killed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/exec": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            cmd: string;
            /** @description seconds; null = no limit */
            timeout?: number | null;
            background?: boolean;
            env?: {
              [key: string]: string;
            };
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ExecResult"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/fork": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            count?: number;
            ttl?: string | null;
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SandboxList"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/extend": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description null keeps it until killed */
            ttl: string | null;
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sandboxes/{id}/files": {
    parameters: {
      query: {
        /** @description relative to /workspace */
        path: string;
      };
      header?: never;
      path: {
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          /** @description relative to /workspace */
          path: string;
        };
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description file bytes */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/octet-stream": string;
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put: {
      parameters: {
        query: {
          /** @description relative to /workspace */
          path: string;
        };
        header?: never;
        path: {
          id: components["parameters"]["id"];
        };
        cookie?: never;
      };
      /** @description up to 100 MB */
      requestBody: {
        content: {
          "application/octet-stream": string;
        };
      };
      responses: {
        /** @description written */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header: {
          "X-Dawnbx": "1";
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            username: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description signed in; sets the session cookie */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Principal"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description signed out */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Principal"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            old: string;
            new: string;
          };
        };
      };
      responses: {
        /** @description changed; every session of the user ends */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              keys: components["schemas"]["Key"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @description Go duration like "720h"; empty = never expires */
            ttl?: string;
            /** @description admins only */
            org?: string;
          };
        };
      };
      responses: {
        /** @description the token is shown only here */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              key: string;
              info: components["schemas"]["Key"];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/keys/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          key: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description revoked */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description latest 200 events */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              events: components["schemas"]["Event"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orgs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              orgs: components["schemas"]["Org"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            id: string;
            name?: string;
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              users: components["schemas"]["User"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            username: string;
            password: string;
            org?: string;
            /** @enum {string} */
            role?: "member" | "admin";
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: components["parameters"]["username"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          username: components["parameters"]["username"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{username}/password": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: components["parameters"]["username"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          username: components["parameters"]["username"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            password: string;
          };
        };
      };
      responses: {
        /** @description changed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/nodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              nodes: components["schemas"]["Node"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/nodes/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description install command for a new worker (audited) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              command: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/nodes/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description removed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/control-plane": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Capability probe. Tells the dashboard which navigation to render; a cluster returns control_plane false. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ControlPlane"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/providers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Providers this control plane can provision with. Phase one is AWS only. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              providers: components["schemas"]["Provider"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/providers/{provider}/regions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: components["parameters"]["provider"];
      };
      cookie?: never;
    };
    /** @description Regions the named provider can provision in with the control plane's configured credential source. A provider that is not available in phase one is 400 provider_unavailable, never an empty list. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: components["parameters"]["provider"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              regions: string[];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/providers/{provider}/instance-types": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: components["parameters"]["provider"];
      };
      cookie?: never;
    };
    /** @description Host sizes the named provider offers, with the current price for the control plane's configured region. The list comes from the provider adapter, never from a table in this contract. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: components["parameters"]["provider"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description The region these prices are for. One fact about the whole response, not one per item, because a size is a catalogue entry and the region was the argument to fetching it. */
              region: string;
              instance_types: components["schemas"]["InstanceTypePrice"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/providers/{provider}/estimate": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: components["parameters"]["provider"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Estimate the fixed charges for a configuration with the named provider. Creates nothing. The returned quote_id must be presented to POST /v1/clusters, which is what makes the price review the gate on spending money. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: components["parameters"]["provider"];
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            region: string;
            instance_type: string;
            disk_gib: number;
            /** @default  */
            domain?: string;
          };
        };
      };
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Estimate"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/clusters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Clusters this control plane manages. Never includes credentials. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              clusters: components["schemas"]["Cluster"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Start provisioning a cluster. Returns the cluster in status provisioning; the dashboard polls GET /v1/clusters/{name} for phase changes. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            name: string;
            region: string;
            instance_type: string;
            disk_gib: number;
            /** @default  */
            domain?: string;
            /** @description from POST /v1/providers/{provider}/estimate */
            quote_id: string;
          };
        };
      };
      responses: {
        /** @description the cluster, provisioning */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Cluster"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/clusters/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components["parameters"]["clusterName"];
      };
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components["parameters"]["clusterName"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Cluster"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    /** @description Delete the cluster and its resources. 409 when workers are still present. Also used by automatic cleanup after a failed provisioning operation. Returns the cluster in status deleting, because the operator is told what is happening rather than left to guess. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components["parameters"]["clusterName"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description the cluster, deleting */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Cluster"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/clusters/{name}/credentials": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components["parameters"]["clusterName"];
      };
      cookie?: never;
    };
    /** @description The cluster's API key and administrator password, in plaintext. Admin only, audited as cluster.credentials.view, and the only response in the API that returns a secret. This is the route that replaces reading them off the host over SSH. The key is minted by the cluster itself once it accepts the injected password, so this returns 409 until the cluster reaches status ready. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components["parameters"]["clusterName"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ClusterCredentials"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/clusters/{name}/rotate": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components["parameters"]["clusterName"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Mint a new administrator password and API key and re-deliver the password to the provider's secret channel. The running cluster keeps both old credentials until an operator applies the new ones. Admin only, audited. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components["parameters"]["clusterName"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description the rotated cluster */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Cluster"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/clusters/{name}/nodes": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components["parameters"]["clusterName"];
      };
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components["parameters"]["clusterName"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              nodes: components["schemas"]["ClusterNode"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Add a worker. 503 cluster_unavailable while the cluster is not ready. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components["parameters"]["clusterName"];
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            instance_type: string;
            disk_gib: number;
          };
        };
      };
      responses: {
        /** @description the node, provisioning */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ClusterNode"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/clusters/{name}/nodes/{node}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components["parameters"]["clusterName"];
        node: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Remove a worker. 409 node_holds_sandboxes when it still holds sandboxes, with the count in the message. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components["parameters"]["clusterName"];
          node: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description removed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      code: string;
      message: string;
      hint?: string;
    };
    Version: {
      version: string;
      api: string;
    };
    Status: {
      version: string;
      free_pct: number;
      warm: number;
      pool_size: number;
    };
    Sandbox: {
      id: string;
      image: string;
      /** @enum {string} */
      status: "running" | "stopped" | "deleting";
      /** @description why it stopped */
      reason?: string;
      parent?: string;
      network: string;
      /** Format: date-time */
      created: string;
      /**
       * Format: date-time
       * @description null = kept until killed
       */
      expires_at: string | null;
      /** Format: date-time */
      restarted_at: string | null;
      org: string;
      node?: string;
      warnings?: string[];
    };
    SandboxList: {
      sandboxes: components["schemas"]["Sandbox"][];
    };
    ExecResult: {
      exit_code: number;
      stdout: string;
      stderr: string;
      /** @description background only */
      pid?: number;
      /** @description background only */
      log?: string;
    };
    Principal: {
      org: string;
      /** @description dashboard sessions */
      user?: string;
      /** @description API keys */
      key_id?: string;
      admin: boolean;
    };
    Key: {
      id: string;
      org: string;
      name: string;
      /** Format: date-time */
      created: string;
      created_by: string;
      /** Format: date-time */
      last_used: string | null;
      /** Format: date-time */
      expires: string | null;
      /** Format: date-time */
      revoked: string | null;
    };
    Event: {
      /** Format: date-time */
      at: string;
      org: string;
      actor: string;
      action: string;
      target: string;
    };
    Org: {
      id: string;
      name: string;
      /** Format: date-time */
      created: string;
    };
    User: {
      id: string;
      org: string;
      username: string;
      /** @enum {string} */
      role: "member" | "admin";
      /** Format: date-time */
      created: string;
    };
    Node: {
      name: string;
      /** @enum {string} */
      role: "server" | "worker";
      ready: boolean;
      /**
       * Format: date-time
       * @description last Ready change
       */
      since: string;
      /** Format: date-time */
      heartbeat: string;
      ip: string;
      kubelet: string;
      sandboxes: number;
    };
    ControlPlane: {
      /** @description true on a control plane */
      control_plane: boolean;
      providers: string[];
      version: string;
    };
    Provider: {
      /** @description aws | gcp | azure */
      id: string;
      /** @description false means the choice is visible but cannot provision */
      available: boolean;
      /** @description How a credential reaches a new host on this provider, in the provider's own words. The guarantee differs by cloud - a cloud with no secret store an instance can read cannot keep the value out of the creation payload - so an operator is told which they are getting rather than the strongest thing the product does anywhere. Empty on a provider this build cannot use, because it cannot deliver anything. */
      delivery?: string;
    };
    InstanceTypePrice: {
      id: string;
      hourly_usd: number;
      monthly_usd: number;
    };
    Estimate: {
      /** @description present this to POST /v1/clusters */
      quote_id: string;
      hourly_usd: number;
      monthly_usd: number;
      /** @description fixed charges only, one row per resource */
      lines: {
        /** @description compute | storage | public_ipv4 */
        label: string;
        hourly_usd: number;
        monthly_usd: number;
      }[];
      /** @description charges deliberately not estimated, shown so the operator is not surprised */
      excluded: string[];
    };
    Cluster: {
      name: string;
      /** @description the provider id; only aws is available in phase one */
      provider: string;
      region: string;
      instance_type: string;
      disk_gib: number;
      domain: string;
      /** @enum {string} */
      status: "provisioning" | "ready" | "failed" | "deleting" | "deleted";
      /** @description current sub-step; empty unless provisioning */
      phase: string;
      /** @description non-secret diagnostic from the bootstrap */
      detail: string;
      hourly_usd: number;
      monthly_usd: number;
      /** @description non-empty only when status is ready */
      url: string;
      /** @description SHA-256 SPKI pin of the cluster certificate */
      tls_pin: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    /** @description The only response in the API that returns plaintext secrets. Admin only, audited, and never included in a list. */
    ClusterCredentials: {
      api_key: string;
      admin_password: string;
    };
    ClusterNode: {
      /** @description Opaque worker handle from the provider, typed back into DELETE /v1/clusters/{name}/nodes/{node}. Returned to the operator because the removal URL needs it; never parsed or interpreted by the control plane. */
      id: string;
      instance_type: string;
      /** @enum {string} */
      status: "provisioning" | "ready" | "failed" | "removing" | "removed";
      detail?: string;
      /** @description last observed count; the cluster is the authority */
      sandboxes: number;
      /** Format: date-time */
      created: string;
    };
  };
  responses: {
    /** @description error */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    id: string;
    username: string;
    clusterName: string;
    provider: "aws";
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
